/**
 * Generate a Markdown report from analysis data
 */

import { formatBytes, formatDuration, formatPercent, formatTimestamp } from '../../shared/utils';

// Interface for export data
interface ExportData {
  title: string;
  sections: ExportSection[];
}

interface ExportSection {
  title: string;
  type: 'stats' | 'table' | 'alert' | 'text';
  content: any;
}

/**
 * Convert analysis data to Markdown string
 */
export function toMarkdown(data: ExportData): string {
  let md = `# ${data.title}\n\n`;
  md += `> Generated by NodeVerdict on ${new Date().toLocaleString()}\n\n`;
  md += `---\n\n`;
  
  for (const section of data.sections) {
    md += `## ${section.title}\n\n`;
    
    switch (section.type) {
      case 'stats':
        md += renderStats(section.content);
        break;
      case 'table':
        md += renderTable(section.content);
        break;
      case 'alert':
        md += renderAlert(section.content);
        break;
      case 'text':
        md += `${section.content}\n\n`;
        break;
    }
  }
  
  return md;
}

function renderStats(stats: Array<{ label: string; value: string }>): string {
  return stats.map(s => `- **${s.label}**: ${s.value}`).join('\n') + '\n\n';
}

function renderTable(table: { headers: string[]; rows: string[][] }): string {
  let md = `| ${table.headers.join(' | ')} |\n`;
  md += `| ${table.headers.map(() => '---').join(' | ')} |\n`;
  for (const row of table.rows) {
    md += `| ${row.join(' | ')} |\n`;
  }
  md += '\n';
  return md;
}

function renderAlert(alert: { level: 'info' | 'warning' | 'error'; message: string }): string {
  const prefix = alert.level === 'error' ? '⚠️' : alert.level === 'warning' ? '⚡' : 'ℹ️';
  return `> ${prefix} **${alert.level.toUpperCase()}**: ${alert.message}\n\n`;
}

/**
 * Generate a self-contained HTML report from Markdown
 */
export function toHtml(markdown: string): string {
  // Simple Markdown to HTML conversion (basic, no external deps)
  const html = markdown
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm, '<h2>$1</h2>')
    .replace(/^# (.+)$/gm, '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/^- (.+)$/gm, '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
    .replace(/\| (.+) \|/g, (match) => {
      // Simple table handling
      return match;
    })
    .replace(/\n\n/g, '</p><p>')
    .replace(/^(.+)$/gm, (match) => {
      if (match.startsWith('<')) return match;
      return match;
    });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NodeVerdict Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; color: #1f2937; background: #f9fafb; }
    h1 { color: #4f46e5; border-bottom: 2px solid #e5e7eb; padding-bottom: 8px; }
    h2 { color: #374151; margin-top: 24px; }
    h3 { color: #4b5563; }
    table { border-collapse: collapse; width: 100%; margin: 12px 0; }
    th, td { border: 1px solid #e5e7eb; padding: 8px 12px; text-align: left; font-size: 14px; }
    th { background: #f3f4f6; font-weight: 600; }
    ul { padding-left: 20px; }
    li { margin: 4px 0; }
    p { line-height: 1.6; }
    .alert { padding: 12px 16px; border-radius: 8px; margin: 12px 0; font-size: 14px; }
    .alert-info { background: #eff6ff; border-left: 4px solid #3b82f6; }
    .alert-warning { background: #fffbeb; border-left: 4px solid #f59e0b; }
    .alert-error { background: #fef2f2; border-left: 4px solid #ef4444; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; text-align: center; }
  </style>
</head>
<body>
  <div class="content">${html}</div>
  <div class="footer">Generated by NodeVerdict on ${new Date().toLocaleString()}</div>
</body>
</html>`;
}

/**
 * Trigger a file download in the browser
 */
export function downloadReport(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}